# Generated by Django 5.2.15 on 2026-06-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_scene_media_path"),
        ("projects", "0004_llmmodel_alter_scene_unique_together_and_more"),
    ]

    operations = []
