# Generated by Django 5.2.15 on 2026-07-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_scene_compose_alter_scene_media_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNING', 'Planning'), ('REFINING', 'Refining'), ('REVIEW', 'Review'), ('IMAGE_REVIEW', 'Image Review'), ('GENERATING', 'Generating'), ('DONE', 'Done'), ('VIDEO_GENERATING', 'Video Generating'), ('FAILED', 'Failed')], default='DRAFT', max_length=20),
        ),
    ]
